            - name: Next Pages
  # You may pin to the exact commit or the version.
  # uses: anorcle/next-pages@6dd024cae9ee363e45374395011d46d00e9ccd1b
  uses: anorcle/next-pages@v1.0
  with:
    # Next.js Export Directory
    inputDir: ./out
    # GitHub Pages Host Directory
    outputDir: ./docs
